#!/bin/sh
#
# @name Quadplane with Control Allocation
#
# @type Standard VTOL
# @class VTOL
#
# @output MAIN1 Motor front right
# @output MAIN2 Motor front left
# @output MAIN3 Motor back right
# @output MAIN4 Motor back left
# @output MAIN5 Motor push
# @output MAIN6 Empty
# @output MAIN7 Elevon right
# @output MAIN8 Elevon left
#
# @maintainer Mason Peterson <mbpeterson70@gmail.com>
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude

. ${R}etc/init.d/rc.ctrlalloc
. ${R}etc/init.d/rc.vtol_defaults

set VEHICLE_TYPE vtol_combmodes
set MAV_TYPE 22

set MIXER direct
set PWM_OUT 12345

set MIXER_AUX direct_aux
set PWM_AUX_OUT 12345

# Necessary to connect correctly with AirSim
param set ASPD_PRIMARY 0

param set-default MPC_USE_HTE 0
param set-default MPC_THR_HOVER 0.5

###############################################################################
#                               Attitude Control                              #
###############################################################################

param set-default MC_ROLL_P   6.0
param set-default MC_PITCH_P  6.0
param set-default MC_YAW_P    2.5
param set-default MC_YAWRATE_MAX 120
param set-default MC_PITCHRATE_MAX 120
param set-default MC_ROLLRATE_MAX 120
param set-default MC_YAW_WEIGHT 1.0

###############################################################################
#                           Angular Velocity Control                          #
###############################################################################

param set-default VM_MASS 5.81
param set-default VM_INERTIA_XX 0.335
param set-default VM_INERTIA_YY 0.140
param set-default VM_INERTIA_ZZ 0.40
param set-default VM_INERTIA_XZ .029

param set-default AVC_Y_K 2.0
# param set-default AVC_x_K 1.0
param set-default AVC_X_P 18.0
param set-default AVC_Y_P 10.0
param set-default AVC_Z_P 18.0
param set-default AVC_X_I 0.5
param set-default AVC_Y_I 0.3
param set-default AVC_Z_I 0.3
param set-default AVC_X_D 0.1
param set-default AVC_Y_D 0.1
param set-default AVC_Z_D 0.1

# param set-default AVC_X_P 18.0
# param set-default AVC_Y_P 20.0
# param set-default AVC_Z_P 18.0
# param set-default AVC_X_I 1.2
# param set-default AVC_Y_I 1.2
# param set-default AVC_Z_I 1.2
# param set-default AVC_X_D 0.1
# param set-default AVC_Y_D 0.00
# param set-default AVC_Z_D 0.1

param set-default AVC_Y_I_LIM 100.0
param set-default AVC_X_I_LIM 100.0
param set-default AVC_Z_I_LIM 100.0

# param set-default AVC_Y_K 3.0
# param set-default AVC_x_K 1.0
# param set-default AVC_X_P 20.0
# param set-default AVC_Y_P 20.0
# param set-default AVC_Z_P 15.0
# param set-default AVC_X_I 0.3
# param set-default AVC_Y_I 0.3
# param set-default AVC_Z_I 0.1
# param set-default AVC_X_D 0.01
# param set-default AVC_Y_D 0.01
# param set-default AVC_Y_D 0.001

###############################################################################
#                              Control Allocation                             #
###############################################################################

param set-default CA_AIRFRAME 4
param set-default CA_METHOD 3

param set-default CA_ACT0_MIN 0.0
param set-default CA_ACT0_MAX 1.0
param set-default CA_ACT1_MIN 0.0
param set-default CA_ACT1_MAX 1.0
param set-default CA_ACT2_MIN 0.0
param set-default CA_ACT2_MAX 1.0
param set-default CA_ACT3_MIN 0.0
param set-default CA_ACT3_MAX 1.0
param set-default CA_ACT4_MIN 0.0
param set-default CA_ACT4_MAX 1.0
param set-default CA_ACT5_MIN 0.0
param set-default CA_ACT5_MAX 1.0
param set-default CA_ACT6_MIN -1.0
param set-default CA_ACT6_MAX 1.0
param set-default CA_ACT7_MIN -1.0
param set-default CA_ACT7_MAX 1.0

# Rotor parameters

param set-default CA_MC_R0_AX 0.0
param set-default CA_MC_R0_AY 0.0
param set-default CA_MC_R0_AZ -1.0
param set-default CA_MC_R0_PX 0.49
param set-default CA_MC_R0_PY 0.37
param set-default CA_MC_R0_PZ 0.0

param set-default CA_MC_R1_AX 0.0
param set-default CA_MC_R1_AY 0.0
param set-default CA_MC_R1_AZ -1.0
param set-default CA_MC_R1_PX 0.49
param set-default CA_MC_R1_PY -0.37
param set-default CA_MC_R1_PZ 0.0

param set-default CA_MC_R2_AX 0.0
param set-default CA_MC_R2_AY 0.0
param set-default CA_MC_R2_AZ -1.0
param set-default CA_MC_R2_PX -0.45
param set-default CA_MC_R2_PY 0.37
param set-default CA_MC_R2_PZ 0.0

param set-default CA_MC_R3_AX 0.0
param set-default CA_MC_R3_AY 0.0
param set-default CA_MC_R3_AZ -1.0
param set-default CA_MC_R3_PX -0.45
param set-default CA_MC_R3_PY -0.37
param set-default CA_MC_R3_PZ 0.0

param set-default CA_MC_R4_AX 1.0
param set-default CA_MC_R4_AY 0.0
param set-default CA_MC_R4_AZ 0.0
param set-default CA_MC_R4_PX -0.41
param set-default CA_MC_R4_PY 0.0
param set-default CA_MC_R4_PZ 0.0

# Frame parameters

param set-default CA_WING_AREA 0.96
param set-default CA_CHORD_LEN 0.378
param set-default CA_SPAN 2.5
param set-default CA_C_ELL_DELTA_A 0.202
param set-default CA_C_M_DELTA_E -0.325
param set-default CA_C_L_DELTA_E 0.7
param set-default CA_C_D_DELTA_E 0.0196

param set-default CA_TLT_SRVO_MIN 0
param set-default CA_TLT_SRVO_MAX 90

param set-default CA_MAX_F_POS_X 100.0
param set-default CA_MAX_F_NEG_X -100.0
param set-default CA_MAX_F_POS_Z 100.0
param set-default CA_MAX_F_NEG_Z -100.0
param set-default CA_NL_ITER_MAX 10

# Lift rotors
param set-default CA_ROT0_CQ0 0.00772
param set-default CA_ROT0_CQ1 -0.00314
param set-default CA_ROT0_CQ2 -0.00926
param set-default CA_ROT0_CT0 0.10101
param set-default CA_ROT0_CT1 -0.05183
param set-default CA_ROT0_CT2 -0.13583
param set-default CA_ROT0_PROP_D .3302
param set-default CA_ROT0_KV 520.0
param set-default CA_ROT0_RES 0.03
param set-default CA_ROT0_I0 1.1
param set-default CA_ROT0_VMAX 24.8

# Push rotor
param set-default CA_ROT1_CQ0 0.00772
param set-default CA_ROT1_CQ1 -0.00314
param set-default CA_ROT1_CQ2 -0.00926
param set-default CA_ROT1_CT0 0.10101
param set-default CA_ROT1_CT1 -0.05183
param set-default CA_ROT1_CT2 -0.13583
param set-default CA_ROT1_PROP_D 0.3302
param set-default CA_ROT1_KV 740.0
param set-default CA_ROT1_RES 0.013
param set-default CA_ROT1_I0 1.72
param set-default CA_ROT1_VMAX 16.5

param set-default CA_SURF0_MAX_ANG 32
param set-default CA_SURF1_MAX_ANG 32
